### ISSUE TITLE
The prolem of Setup pyv8 on Centos5.6, Python2.7

### ISSUE THREAD

**Issue by eukreign** [eukreign/python-v8#19]
_From [jayrabo...@gmail.com](https://code.google.com/u/102489936668200815597/) on July 19, 2013 05:49:50_

I try to setup pyv8 on Centos5.6, but have some problems.I do this installation on 2ways:
1)i download V8 and pyv8, than 
# export V8_HOME=/usr/local/src/v8
# python2.7 setup.py build

and have some errors:

PYTHONPATH="/usr/local/src/v8/tools/generate_shim_headers:" \
    GYP_GENERATORS=make \
    build/gyp/gyp --generator-output="out" build/all.gyp \
                  -Ibuild/standalone.gypi --depth=. \
                  -Dv8_target_arch=ia32 \
                  -S.ia32  -Dcomponent=shared_library -Dv8_enable_backtrace=1 -Dv8_enable_extra_checks=0 -Dv8_enable_gdbjit=0 -Dwerror='' -Darm_fpu=default -Darm_float_abi=default
ERROR: build v8 from SVN failed: code=2
DEBUG: Traceback (most recent call last):
  File "build/gyp/gyp", line 15, in ?
    import gyp
  File "build/gyp/pylib/gyp/**init**.py", line 8, in ?
    import gyp.input
  File "build/gyp/pylib/gyp/input.py", line 856
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
make: **\* [out/Makefile.ia32] Error 1

**_and in the end ofcompilation process**_
g++ -pthread -shared build/temp.linux-i686-2.7/src/Utils.o build/temp.linux-i686-2.7/src/Exception.o build/temp.linux-i686-2.7/src/Context.o build/temp.linux-i686-2.7/src/Engine.o build/temp.linux-i686-2.7/src/Wrapper.o build/temp.linux-i686-2.7/src/Debug.o build/temp.linux-i686-2.7/src/Locker.o build/temp.linux-i686-2.7/src/AST.o build/temp.linux-i686-2.7/src/PrettyPrinter.o build/temp.linux-i686-2.7/src/PyV8.o -L/usr/local/lib -L/usr/local/src/v8/out/ia32.release/obj.target/tools/gyp/ -lrt -lboost_python -lboost_thread -lboost_system -lv8_base.ia32 -lv8_snapshot -o build/lib.linux-i686-2.7/_PyV8.so
/usr/bin/ld: cannot find -lv8_base.ia32
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1

2)setup pyv8 trought pip install
# pip -v install pyv8

i i have some errors(added in attachment)

**Attachment:** [log.rtf](http://code.google.com/p/pyv8/issues/detail?id=190)

_Original issue: http://code.google.com/p/pyv8/issues/detail?id=190_

**Comment by eukreign** [comment]
_From [jayrabo...@gmail.com](https://code.google.com/u/102489936668200815597/) on July 24, 2013 02:01:33_

Now situation is better but :
No emulation specific options

```
ar: supported targets: elf32-i386 a.out-i386-linux efi-app-ia32 elf64-x86-64 elf64-little elf64-big elf32-little elf32-big srec symbolsrec tekhex binary ihex trad-core

make[1]: *** [/usr/local/src/venv/build/pyv8/build/v8/out/ia32.release/obj.target/tools/gyp/libv8_nosnapshot.ia32.a] Error 1

make[1]: *** Waiting for unfinished jobs....

make: *** [ia32.release] Error 2
```

**Attachment:** [pip.log](http://code.google.com/p/pyv8/issues/detail?id=190#hc1)

**Comment by eukreign** [comment]
_From [flier...@gmail.com](https://code.google.com/u/106022808272130273369/) on August 13, 2013 20:12:12_

It seems your v8 can't be linked with `ar` command, what's your ar version?

 ar: illegal option -- T

```
Usage: ar [emulation options] [-]{dmpqrstx}[abcfilNoPsSuvV] [member-name] [count] archive-file file...

       ar -M [<mri-script]
```

**Comment by eukreign** [comment]
_From [jayrabo...@gmail.com](https://code.google.com/u/102489936668200815597/) on August 14, 2013 02:38:12_

ar -V
GNU ar 2.17.50.0.6-20.el5_8.3 20061020
Copyright 2005 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License.  This program has absolutely no warranty.

**Comment by eukreign** [comment]
_From [jmalo...@gmail.com](https://code.google.com/u/106682831104422461380/) on November 17, 2013 17:03:52_

I think you're gonna need a more recent binutils for this.
